services:
  - type: web
    name: portfolio
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Admin__Password
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: Cloudinary__UploadPreset
        sync: false
