using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable

namespace portfolio.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Certifications" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(180),
                    "NameTr" character varying(180),
                    "Issuer" character varying(160),
                    "IssuerTr" character varying(160),
                    "IssueDate" text,
                    "IssueDateTr" text,
                    "CredentialUrl" character varying(500),
                    "Description" text,
                    "DescriptionTr" text,
                    CONSTRAINT "PK_Certifications" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Educations" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "School" character varying(160),
                    "SchoolTr" character varying(160),
                    "Degree" text,
                    "DegreeTr" character varying(200),
                    "StartDate" text,
                    "StartDateTr" text,
                    "EndDate" text,
                    "EndDateTr" text,
                    "Description" text,
                    "DescriptionTr" text,
                    CONSTRAINT "PK_Educations" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Experiences" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Role" text,
                    "RoleTr" character varying(200),
                    "Company" character varying(160) NOT NULL,
                    "Location" text,
                    "LocationTr" text,
                    "StartDate" text,
                    "StartDateTr" text,
                    "EndDate" text,
                    "EndDateTr" text,
                    "Description" text,
                    "DescriptionTr" text,
                    CONSTRAINT "PK_Experiences" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Profiles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "FirstName" text NOT NULL,
                    "LastName" text NOT NULL,
                    "Title" text,
                    "TitleTr" character varying(200),
                    "Email" character varying(160),
                    "Phone" character varying(80),
                    "Location" character varying(160),
                    "Summary" text,
                    "SummaryTr" text,
                    "LinkedInUrl" text,
                    "GitHubUrl" text,
                    "PhotoUrl" character varying(500),
                    "CvUrl" character varying(500),
                    CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Projects" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(160),
                    "NameTr" character varying(160),
                    "Summary" text,
                    "SummaryTr" text,
                    "DisplayOrder" integer NOT NULL DEFAULT 0,
                    "Technologies" text,
                    "TechnologiesTr" text,
                    "Url" text,
                    "ImageUrl" character varying(500),
                    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Skills" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(100),
                    "NameTr" character varying(100),
                    CONSTRAINT "PK_Skills" PRIMARY KEY ("Id")
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Certifications");

            migrationBuilder.DropTable(
                name: "Educations");

            migrationBuilder.DropTable(
                name: "Experiences");

            migrationBuilder.DropTable(
                name: "Profiles");

            migrationBuilder.DropTable(
                name: "Projects");

            migrationBuilder.DropTable(
                name: "Skills");
        }
    }
}
